### ISSUE TITLE
Erro ao executar agendamento publicarProtocoloIntegrado

### ISSUE THREAD

**Issue by danielcoelhocgu** [pengovbr/mod-sei-protocolo-integrado#12]
**Descreva o erro**
Ao executar o agendamento ProtocoloIntegradoAgendamentoRN::publicarProtocoloIntegrado, ocorre um erro (Object of class DateTime could not be converted to string) no processamento do campo `dth_abertura` da tabela `atividade` do SEI. Pelo que investiguei, o código esperava que fosse retornado um objeto do tipo string e foi retornado um objeto do tipo DateTime.

O problema está na forma com que a função `consultarAtividadesPublicacao` faz a consulta no banco.
https://github.com/supergovbr/mod-sei-protocolo-integrado/blob/2c744055740772db72b94d2526395cee54384ae2/src/bd/ProtocoloIntegradoMonitoramentoProcessosBD.php#L239
Ao usar a função `consultarSql` diretamente, me parece que os campos são retornados da forma como o driver PHP do banco de dados utilizado retorna.

No caso do banco SQLServer, o driver SQLSRV por padrão retorna os campos de data como objetos DateTime e não como string. (https://learn.microsoft.com/en-us/sql/connect/php/how-to-retrieve-date-and-time-type-as-strings-using-the-sqlsrv-driver?view=sql-server-ver16).

O framework do SEI até corrige isso, mas só quando se usa as funções da classe InfraBD (Ex: listar, consultar, etc). Para não mudar muito o código, sugiro utilizar a função `formatarLeituraDth` da interface InfraIBanco ao ler o valor do campo `dth_abertura`. Irei fazer um pull request com a sugestão.

-----

**Para reproduzir**
Execute o agendamento ProtocoloIntegradoAgendamentoRN::publicarProtocoloIntegrado, seja de forma manual ou automática, em um ambiente do SUPER com banco de dados SQLServer.

-----

**Comportamento esperado**
Agendamento ser executado sem falhas.

-----

**Contexto da falha (Por favor, complete a seguinte informação):**
 - Versão do sistema: Módulo 2.3.1 / SUPER 4.0.3.3
 - Navegador: Firefox
 - Perfil do Usuário: administrador
 - Banco de Dados: SQLServer

-----
**Log de Erros**
```
Agendamento FALHOU (sdp-super-ap1.cgu.local)

Servidor: sdp-super-ap1.cgu.local

Data/Hora: 03/01/2023 01:00:28

Comando: ProtocoloIntegradoAgendamentoRN::publicarProtocoloIntegrado()

Erro: Descrição:
Erro acontecido

Mensagem:
Erro acontecido

Trilha de Processamento:
#0 /opt/v400/infra/infra_php/formularios/rn/InfraAgendamentoTarefaRN.php(621): ProtocoloIntegradoAgendamentoRN->publicarProtocoloIntegrado(Array)
#1 /opt/v400/infra/infra_php/InfraAgendamentoTarefa.php(198): InfraAgendamentoTarefaRN->executar(Object(InfraAgendamentoTarefaDTO))
#2 /opt/v400/sei/scripts/AgendamentoTarefaSEI.php(27): InfraAgendamentoTarefa->executar('no-reply-sei@cg...', 'sesol@cgu.gov.b...')
#3 {main}

Descrição Original:
Exception: 'Fatal Error: /opt/v400/sei/web/modulos/mp/mod-sei-protocolo-integrado/rn/ProtocoloIntegradoMonitoramentoProcessosRN.php linha:873.
Object of class DateTime could not be converted to string
' in /opt/v400/infra/infra_php/Infra.php:207
Stack trace:
#0 [internal function]: infraGerarExcecao(4096, 'Object of class...', '/opt/v400/sei/w...', 873, Array)
#1 /opt/v400/sei/web/modulos/mp/mod-sei-protocolo-integrado/rn/ProtocoloIntegradoMonitoramentoProcessosRN.php(873): str_replace('/', '-', Object(DateTime))
#2 /opt/v400/sei/web/modulos/mp/mod-sei-protocolo-integrado/rn/ProtocoloIntegradoMonitoramentoProcessosRN.php(145): ProtocoloIntegradoMonitoramentoProcessosRN->publicarProcessosMonitorados(Array)
#3 /opt/v400/infra/infra_php/InfraRN.php(140): ProtocoloIntegradoMonitoramentoProcessosRN->publicarProcessosConectado(Object(ProtocoloIntegradoParametrosDTO))
#4 /opt/v400/sei/web/modulos/mp/mod-sei-protocolo-integrado/rn/ProtocoloIntegradoAgendamentoRN.php(34): InfraRN->__call('publicarProcess...', Array)
#5 /opt/v400/infra/infra_php/formularios/rn/InfraAgendamentoTarefaRN.php(621): ProtocoloIntegradoAgendamentoRN->publicarProtocoloIntegrado(Array)
#6 /opt/v400/infra/infra_php/InfraAgendamentoTarefa.php(198): InfraAgendamentoTarefaRN->executar(Object(InfraAgendamentoTarefaDTO))
#7 /opt/v400/sei/scripts/AgendamentoTarefaSEI.php(27): InfraAgendamentoTarefa->executar('no-reply-sei@cg...', 'sesol@cgu.gov.b...')
#8 {main}

Trilha de Processamento Original:
0 [internal function]: infraGerarExcecao(4096, 'Object of class...', '/opt/v400/sei/w...', 873, Array)
1 /opt/v400/sei/web/modulos/mp/mod-sei-protocolo-integrado/rn/ProtocoloIntegradoMonitoramentoProcessosRN.php(873): str_replace('/', '-', Object(DateTime))
2 /opt/v400/sei/web/modulos/mp/mod-sei-protocolo-integrado/rn/ProtocoloIntegradoMonitoramentoProcessosRN.php(145): ProtocoloIntegradoMonitoramentoProcessosRN->publicarProcessosMonitorados(Array)
3 /opt/v400/infra/infra_php/InfraRN.php(140): ProtocoloIntegradoMonitoramentoProcessosRN->publicarProcessosConectado(Object(ProtocoloIntegradoParametrosDTO))
4 /opt/v400/sei/web/modulos/mp/mod-sei-protocolo-integrado/rn/ProtocoloIntegradoAgendamentoRN.php(34): InfraRN->__call('publicarProcess...', Array)
5 /opt/v400/infra/infra_php/formularios/rn/InfraAgendamentoTarefaRN.php(621): ProtocoloIntegradoAgendamentoRN->publicarProtocoloIntegrado(Array)
6 /opt/v400/infra/infra_php/InfraAgendamentoTarefa.php(198): InfraAgendamentoTarefaRN->executar(Object(InfraAgendamentoTarefaDTO))
7 /opt/v400/sei/scripts/AgendamentoTarefaSEI.php(27): InfraAgendamentoTarefa->executar('no-reply-sei@cg...', 'sesol@cgu.gov.b...')
8 {main}
```

**Comment by danielcoelhocgu** [comment]
Como não tenho permissão para subir um branch no repositório e abrir um pull request, estou anexando o patch que resolve o erro. Testei no nosso ambiente do SUPER da CGU e funcionou corretamente. Conseguimos voltar a publicar os processos.

[0001-Corrigido-erro-no-processamento-do-campo-dth_abertur.patch](https://github.com/supergovbr/mod-sei-protocolo-integrado/files/10343945/0001-Corrigido-erro-no-processamento-do-campo-dth_abertur.patch)

**Comment by yurioliveiramgi** [comment]
@amelquia , gentileza verificar se essa correção subiu em alguma versão do módulo e se ainda é necessária essa correção.

Se for o caso, avaliar a inserção do PR na nova versão do módulo.

**Comment by amelquia** [comment]
> [@amelquia](https://github.com/amelquia) , gentileza verificar se essa correção subiu em alguma versão do módulo e se ainda é necessária essa correção.
> 
> Se for o caso, avaliar a inserção do PR na nova versão do módulo.

@caduvieira 
se possível, pode verificar o questionamento do Yuri, por favor? Obg.

**Comment by caduvieira** [comment]
Não foi incorporada tanto que a CGU apagou o fork. Pode ser feito a tentativa de reproduzir. O tratamento de datas foi alterado em alguns pontos na 3.0.3.

**Comment by yurioliveiramgi** [comment]
@caduvieira , você acha relevante tentar reproduzir ou o tratamento de datas suprime a necessidade de correção trazida nessa issue?
A pergunta é mais para sabermos se a issue possui ou não necessidade de desenvolvimento para eventual incorporação à 3.0.4 do módulo.
Obrigado

**Comment by caduvieira** [comment]
Melhor tentar reproduzir

**Comment by yurioliveiramgi** [comment]
Perfeito, @caduvieira . Obrigado.
Como a Andrea está de férias, poderia solicitar que alguém da equipe tentasse reproduzir a situação utilizando a versão 3.0.3 do módulo, por gentileza? 
Obrigado.

**Comment by caduvieira** [comment]
@NinetiesPaul por favor tentar reproduzir esse comportamento para esse banco de dados. Na vertsão 3.0.3 e no SEI 5.0.4 por favor

**Comment by NinetiesPaul** [comment]
@caduvieira Teste realizado nas versões de modulo e core sugeridas. Nenhum erro pode ser observado.

**Comment by yurioliveiramgi** [comment]
@caduvieira , considerando que o erro não pode ser reproduzido, com base nas configurações inicialmente reportadas (versão de SPE e módulo), estaremos concluindo essa issue.
Caso uma nova situação seja reportada, retornaremos à análise.

Obrigado.
